global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'autosre-backend'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['autosre-backend:8000']

  - job_name: 'faulty-service'
    static_configs:
      - targets: ['faulty-service:8080']
